common: &common
  adapter: postgresql
  encoding: utf8
  pool: 25
  username: postgres
  host: localhost
  password: 123123123

development:
  database: thewind_development
  min_messages: warning
  <<: *common

production:
  adapter: postgresql
  encoding: utf8
  pool: 25
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  database: thewind_test
  min_messages: warning
  <<: *common


