common: &common
  adapter: postgresql
  encoding: utf8
  pool: 25
  username: postgres
  host: localhost
  password: 123123123

development:
  database: demo_development
  min_messages: warning
  <<: *common

production:
  adapter: postgresql
  encoding: utf8
  pool: 25
  database: <%= ENV['TIFANY_DATABASE_NAME'] %>
  username: <%= ENV['TIFANY_DATABASE_USERNAME'] %>
  password: <%= ENV['TIFANY_DATABASE_PASSWORD'] %>

test:
  database: demo_test
  min_messages: warning
  <<: *common


